name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v1

  test:
    needs: lint
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run across a mixture of Python versions and operating systems
        include:
        - os: ubuntu-latest
          python-version: "3.11"
        - os: macos-latest
          python-version: "3.10"
        - os: windows-latest
          python-version: "3.9"
        - os: ubuntu-latest
          python-version: "3.8"

    steps:
      - uses: neuroinformatics-unit/actions/test@v1
        with:
          python-version: ${{ matrix.python-version }}
